USE prepwise_db;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE alerts;
TRUNCATE TABLE shelter_locations;
TRUNCATE TABLE drills;
TRUNCATE TABLE emergency_kits;
TRUNCATE TABLE certificates;
TRUNCATE TABLE disaster_reports;
TRUNCATE TABLE progress;
TRUNCATE TABLE resources;
TRUNCATE TABLE modules;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

-- MODULES (using real course IDs)
INSERT INTO modules (course_id, title, content, order_num, duration_mins, is_active, created_at, updated_at) VALUES

-- Course 1: Fundamentals of Disaster Preparedness (General)
(1,'Understanding Disaster Risk in India','India is one of the world most disaster-prone countries, affected by 26 of 35 major disaster types recognized by the United Nations. Every year, an average of 50 million people are affected by natural disasters in India. The country faces floods (affecting 33 million annually), cyclones (coastline of 7,516 km), earthquakes (57% of land in seismic zones III-V), droughts, heatwaves, landslides, and tsunamis. The National Disaster Management Authority (NDMA) was established under the Disaster Management Act 2005 following the catastrophic 2004 Indian Ocean Tsunami and 2001 Bhuj earthquake. Understanding your local hazard profile is the first step to preparedness. Check ndma.gov.in for your district hazard map.',1,20,1,NOW(),NOW()),
(1,'The Disaster Management Cycle','Disaster management follows a four-phase cycle that every citizen should understand: (1) Mitigation — reducing risk before disaster strikes through building codes, early warning systems, land-use planning, and community awareness. (2) Preparedness — planning, training, stockpiling supplies, and conducting drills before disasters occur. (3) Response — immediate actions during and just after disaster: evacuation, search and rescue, first aid, and relief distribution. (4) Recovery — rebuilding communities, restoring livelihoods, and improving resilience after disaster. India NDMA coordinates all four phases through State Disaster Management Authorities (SDMAs) and District Disaster Management Authorities (DDMAs) at local level.',2,20,1,NOW(),NOW()),
(1,'Building Your Family Disaster Plan','Every Indian household needs a Family Disaster Plan: (1) Identify hazards specific to your area — flood zone, seismic zone, cyclone belt, or industrial area. (2) Map two evacuation routes from your home to higher ground or designated shelter. (3) Choose a family meeting point outside your home and one outside your neighbourhood if separated. (4) Designate an out-of-city contact person for family members to check in with — long-distance calls often work when local lines are jammed. (5) Make a list of emergency numbers: 112 (unified emergency), 108 (ambulance), 1078 (NDMA), local district control room. (6) Practice the plan with all family members including children twice a year.',3,25,1,NOW(),NOW()),
(1,'The 72-Hour Emergency Kit — India Standard','After any major disaster, government help typically takes 24-72 hours to reach you. Your emergency kit must sustain your family for this period. NDMA recommended kit includes: Water — 4 litres per person per day minimum. Food — ready-to-eat non-perishable items like khakhra, chivda, energy bars, dry fruits. Medicines — prescription medications for 7 days plus basic first aid supplies. Documents — Aadhaar, insurance papers, land records in waterproof bag. Tools — torch with batteries, battery radio for AIR updates, emergency whistle, multi-tool. Communication — fully charged power bank, emergency contact list on paper. Store kit in a grab-and-go bag near your main exit door. Check and refresh every 6 months.',4,25,1,NOW(),NOW()),

-- Course 2: Emergency First Aid & CPR (Medical)
(2,'CPR — Hands-Only Basic Life Support','Cardiac arrest kills within 4-6 minutes without intervention. In India, fewer than 1% of out-of-hospital cardiac arrests survive due to low bystander CPR rates. Hands-only CPR technique: (1) Confirm scene is safe. (2) Tap shoulders and shout — are you okay? (3) Call 108 immediately or ask someone specific to call. (4) Tilt head back, lift chin — check for breathing for no more than 10 seconds. (5) Place heel of hand on centre of chest — lower half of sternum only. (6) Press hard and fast at least 5 cm deep at 100-120 compressions per minute — tempo of Stayin Alive by Bee Gees. (7) Allow full chest recoil — do not lean between compressions. Continue until 108 ambulance arrives.',1,30,1,NOW(),NOW()),
(2,'Bleeding Control and Wound Management','Uncontrolled bleeding is the leading cause of preventable death in trauma. Technique: Apply firm direct pressure with a clean cloth. Do not remove cloth if soaked — add more on top and press harder. For limb bleeding not controlled by pressure within 10 minutes, apply tourniquet 5-7 cm above the wound. Improvised tourniquet: folded cloth at least 5 cm wide tied tightly and twisted with a stick until bleeding stops. Write time of application on patient. Note: never use wire, rope, or thin cord. Wound cleaning: Irrigate with clean water for 5 minutes — not hydrogen peroxide which damages tissue. Cover with clean dressing. Watch for infection signs after 24-48 hours: increasing redness, warmth, swelling, discharge.',2,25,1,NOW(),NOW()),
(2,'Fractures, Burns, and Spinal Injuries','Fracture management: Immobilize joint above and below fracture using rigid splint — wooden plank, rolled newspaper, or umbrella — padded with cloth. Do not attempt to realign bone. Open fractures with bone visible: cover with clean dressing only. Burns: Cool with running water for minimum 20 minutes — not ice, not butter, not toothpaste. Cover with clean non-fluffy material. Do not burst blisters. Spinal injury: If patient has fallen from height or had significant head or neck impact, assume spinal injury. Do not bend, twist, or move neck. Use log-roll technique with minimum 3 people to move patient onto flat surface. Helmet removal only if patient cannot breathe — requires two-person technique.',3,25,1,NOW(),NOW()),
(2,'Snakebite, Heatstroke, and Drowning','Snakebite kills 50,000 Indians annually — highest in world. Response: Immobilize bitten limb at or below heart level. Remove all jewellery from bitten limb immediately. Do NOT cut the wound, suck the venom, apply tourniquet, or apply any traditional remedies. Transport urgently to nearest government hospital — only WHO-approved polyvalent anti-venom works. Heatstroke — core temperature above 40 degrees, confusion, hot dry skin: Cool immediately with water, fan, and ice packs to neck, armpits, and groin. Call 108. Drowning: Remove from water using rope or clothing — do not enter fast-moving water without training. Begin CPR immediately if not breathing normally. All drowning victims need hospital evaluation regardless of initial appearance.',4,30,1,NOW(),NOW()),

-- Course 11: Flood Safety & Survival
(11,'Understanding Floods and Early Warning India','India experiences three types of floods: riverine floods from monsoon overflow of major rivers, flash floods from sudden intense rainfall in hilly terrain, and coastal flooding from cyclone storm surges. The Brahmaputra, Ganga, Mahanadi, Godavari, Krishna, and Cauvery river systems cause most riverine flooding. Over 40 million hectares of Indian land is flood-prone. The Central Water Commission monitors over 5,000 river gauging stations and issues three-tier flood warnings: Watch (below danger level), Alert (approaching danger level), and Danger (above danger level). Download the Sachet NDMA app and register your location to receive flood warnings. Also monitor indiawris.gov.in for real-time river level data in your district.',1,20,1,NOW(),NOW()),
(11,'Flood Preparedness at Home and Community','Before monsoon season every year: (1) Know if your home is in a flood-prone zone — check district flood control map. (2) Store drinking water in elevated locations. (3) Waterproof your important documents — Aadhaar, land records, insurance — in sealed ziplock bags placed in a waterproof container. (4) Keep a 72-hour emergency kit on upper floor. (5) Know two evacuation routes to higher ground and the location of your nearest government flood shelter. (6) Trim trees near your home. (7) Keep emergency numbers saved: 1078 NDMA, 112 police, 108 ambulance, and your district flood control room number. Community action: Participate in your local ward flood preparedness meeting organized by your municipality before June 1 every year.',2,25,1,NOW(),NOW()),
(11,'During and After Flood — Safe Actions','During flood warning: Move immediately to upper floors or higher ground — do not delay waiting to see if it floods. Turn off electricity at main breaker before water enters your home. Never touch electrical equipment while standing in water. Do not walk or drive through floodwater — 15 cm of fast-moving water knocks adults down and 30 cm can sweep away a vehicle. Avoid all floodwater contact — it contains sewage, industrial chemicals, and displaced venomous snakes. If trapped on roof: signal with bright cloth or torch and wait for rescue. Call 112. After flood: Do not return until authorities declare safe. Boil all water. Watch for leptospirosis symptoms — fever, muscle pain, red eyes — appearing 2-14 days after flood exposure. Contact district administration for SDRF compensation claim.',3,20,1,NOW(),NOW()),

-- Course 12: Earthquake Response Training
(12,'Seismic Zones and Building Safety in India','India is divided into four seismic zones by the Bureau of Indian Standards per IS 1893:2016. Zone II — low damage risk: parts of South India, Rajasthan. Zone III — moderate: Most of Maharashtra, Madhya Pradesh, parts of UP. Zone IV — high: Delhi, J&K, Himachal Pradesh, UP, Bihar. Zone V — very high: Entire Northeast India, Uttarakhand, Kashmir, parts of Gujarat (Kutch), and Andaman & Nicobar Islands. Over 60% of India land area is in Zone III or above. Buildings constructed before 1985 may not meet any seismic code requirements. The 2001 Bhuj earthquake killed 20,085 — most in non-engineered masonry buildings. Check your seismic zone at bhukosh.gsi.gov.in and consult a structural engineer if your building shows diagonal cracks at window corners.',1,25,1,NOW(),NOW()),
(12,'Drop Cover Hold — Earthquake Response','During ground shaking — the only three things that matter: DROP to hands and knees immediately. This protects you from being thrown down and keeps you mobile. COVER your head and neck under a sturdy table or desk. If no table is available, cover head and neck with both arms and get against an interior wall away from windows. HOLD ON to your shelter until shaking completely stops — earthquakes can last from seconds to over 2 minutes. Critical myths to unlearn: Do NOT run outside — most earthquake injuries occur when people run through falling debris. Do NOT stand in doorways — this dangerous myth has caused many deaths. Do NOT use elevators. If in bed, stay there and cover head with pillow.',2,20,1,NOW(),NOW()),
(12,'Post-Earthquake Safety and Aftershocks','After shaking stops: Check yourself for injuries before moving. Expect aftershocks — they can occur for days to months and may be strong enough to collapse already-weakened buildings. Inspect for hazards before moving through building: Gas leak — smell or hissing sound means open windows, leave immediately, do not use any switches, call gas emergency from outside. Electrical hazard — damaged wiring, sparks, smell of burning. Structural damage — diagonal cracks at window corners, separation of walls from ceiling or floor, visible steel reinforcing bars, leaning walls. Do not re-enter any building with these signs. Contact municipality for structural safety assessment. Register with your district DDMA at 1800-180-4188.',3,25,1,NOW(),NOW()),

-- Course 13: Cyclone Preparedness - Bay of Bengal
(13,'Bay of Bengal Cyclone Formation and Warnings','The Bay of Bengal is one of the most cyclone-active ocean basins in the world, generating over 7% of global tropical cyclones annually. Cyclone season: April to June and October to December. States most vulnerable: Odisha, Andhra Pradesh, Tamil Nadu, West Bengal, and Puducherry. IMD four-stage warning system: Pre-Cyclone Watch issued 96 hours before landfall, Cyclone Alert 48 hours before, Cyclone Warning 24 hours before, Post-Landfall Outlook after landfall. IMD color-coded warnings: Green — no threat, Yellow — be updated, Orange — be prepared to act, Red — take action immediately. Track cyclones in real time at mausam.imd.gov.in. Subscribe to IMD alerts via the Mausam app. Storm surge — the wall of seawater pushed ashore by cyclone winds — is the deadliest component, not wind.',1,25,1,NOW(),NOW()),
(13,'Cyclone Safety Actions Before During and After','Before cyclone: Reinforce roof with additional fasteners. Board windows with plywood or shutters. Trim all trees near the house. Bring inside gas cylinders, two-wheelers, and all loose objects. Fill all containers with water — supply will be cut. Charge all devices and power banks. Know your nearest cyclone shelter. During cyclone: Stay in the innermost room on lowest floor if not flood-prone. Keep away from all windows. If roof begins to lift, lie flat under strongest table available. Do NOT go outside during the eye — the second wall follows. After cyclone: Treat every downed power line as live — do not approach. Do not enter damaged buildings. Boil all water. Report trapped persons to SDRF helpline. Cyclone Fani 2019 key achievement: Odisha evacuated 1.2 million people in 48 hours achieving near-zero deaths through years of community preparedness.',2,25,1,NOW(),NOW()),

-- Course 16: Heatwave Survival Guide
(16,'Heatwave Science and India Vulnerability','A heatwave in India is officially declared when the maximum temperature exceeds 40 degrees Celsius in plains (45 degrees in desert areas) or is 4.5 degrees above the normal maximum for that date. India has seen a 300% increase in heatwave frequency over the past 50 years due to climate change. The 2015 Andhra Pradesh and Telangana heatwave was India deadliest heat event, killing 2,500 in two weeks. Most vulnerable populations: outdoor labourers including construction workers, farmers, and daily wage workers; elderly persons above 65; children under 5; persons with heart disease, diabetes, or respiratory conditions. Heat Index — how hot it actually feels — combines temperature and humidity. At 38 degrees Celsius with 80% relative humidity, the effective temperature on the human body is 55 degrees.',1,20,1,NOW(),NOW()),
(16,'Heat Illness Recognition and Emergency Response','Heat cramps: muscle spasms during exercise in heat — move to cool place, drink ORS, rest. Heat exhaustion: heavy sweating, weakness, cold pale clammy skin, weak pulse, nausea — move to cool place immediately, apply wet cloth, give ORS, call 104. Heatstroke — medical emergency: temperature above 40 degrees, confusion or altered consciousness, hot dry skin (sweating may stop), rapid strong pulse — Call 108 immediately. While waiting: cool the person rapidly by any means available — pour water, fan, ice packs to neck, armpits, and groin. Do NOT give fluids to someone who is confused. Prevention: Drink water every 30 minutes even when not thirsty. ORS sachets are superior to plain water for anyone doing outdoor work. Never leave any person or animal in a parked vehicle — interior temperature reaches 70 degrees in 20 minutes.',2,20,1,NOW(),NOW()),

-- Course 17: Landslide Risk & Safety
(17,'Landslide Hazards Across India','India records 500-1,000 landslide deaths annually with significant under-reporting in remote Himalayan and Northeast regions. The Geological Survey of India has mapped 0.42 million square kilometres as landslide-prone — approximately 12.6% of India total land area. High-risk states: Uttarakhand, Himachal Pradesh, Jammu and Kashmir, all Northeast states especially Manipur and Mizoram, Kerala (Western Ghats), and Maharashtra (Sahyadri range). Primary triggers: intense monsoon rainfall exceeding 150mm per day, deforestation for agriculture and road construction, unregulated slope cutting for hill roads, and earthquake shaking in mountain terrain. The July 2024 Wayanad landslides in Kerala killed 231 people and displaced 10,000 in a single night, triggered by 572mm of rainfall in 48 hours on slopes denuded for tea plantations.',1,25,1,NOW(),NOW()),
(17,'Landslide Warning Signs and Safe Evacuation','Community warning signs to watch during heavy rainfall: New cracks appearing in ground, roads, or house walls especially diagonal cracks at corners. Tilting or newly leaning trees, fence posts, or utility poles. Doors and windows that suddenly stick or no longer close properly — indicates ground movement. Unusual sounds: rumbling, cracking of trees, or rushing water sounds. Streams suddenly becoming very muddy or turbid. Sudden decrease in stream flow (debris dam forming upstream — very dangerous, sudden outburst flooding follows). Safe evacuation: Move immediately to higher ground or perpendicular to slope — never run downhill along the slide path. If caught in slide: curl into tight ball, protect head with arms. After landslide: secondary slides very common for 24 hours. Stay away. Report to 112.',2,20,1,NOW(),NOW());

-- ALERTS
INSERT INTO alerts (title, level, message, target_group, sent_by, is_active, ai_summary, created_at, updated_at) VALUES
('RED ALERT: Cyclone VAYU Approaching Odisha-AP Coast','critical','The India Meteorological Department has issued a RED alert for coastal Odisha and Andhra Pradesh. Cyclonic Storm VAYU has intensified into a Severe Cyclonic Storm and is expected to make landfall near Gopalpur, Odisha within 24 hours. Maximum sustained wind speed: 150-160 km/h gusting to 180 km/h. Dangerous storm surge of 2-4 metres expected along coastal areas. Mandatory evacuation ordered for all residents within 10 km of coastline. Relief camps are operational at 847 designated cyclone shelters across both states. NDRF teams have been deployed to Bhubaneswar, Puri, Berhampur, and Gopalpur. Do NOT venture into the sea under any circumstances. Keep identity documents and essential medicines in waterproof bags. Emergency helpline: 1078.','all',1,1,'RED ALERT: Cyclone VAYU approaching Odisha-AP coast. Landfall in 24 hrs. Winds 150-180 km/h. Storm surge 2-4 metres. Mandatory coastal evacuation. NDRF deployed. Call 1078.',NOW() - INTERVAL 2 HOUR,NOW()),
('CRITICAL FLOOD: Brahmaputra Above Danger Level — Assam','critical','The Central Water Commission reports the Brahmaputra River at Guwahati has reached 87.3 metres, crossing the danger level of 85.1 metres. Heavy rainfall upstream in Arunachal Pradesh (380mm in 48 hours) has caused embankment breaches in Dhubri, Barpeta, and Morigaon districts. Approximately 2.3 lakh people across 892 villages are currently affected. NDRF teams are conducting active rescue operations at Pathsala and Nalbari. Flood relief camps established at 234 schools and community halls across the state. Do not use flooded roads — NH-17 and NH-27 are partially submerged. All residents in low-lying areas must move to higher ground immediately. State flood helpline: 1800-345-3501.','all',1,1,'CRITICAL: Brahmaputra above danger level in Assam. 2.3 lakh people affected across 892 villages. NDRF deployed. Move to higher ground immediately. Helpline: 1800-345-3501.',NOW() - INTERVAL 5 HOUR,NOW()),
('ORANGE ALERT: Severe Heatwave — North India April 6 to 9 2026','warning','IMD has issued an Orange Alert for severe heatwave conditions across Delhi NCR, Rajasthan, Haryana, Punjab, and western Uttar Pradesh valid from April 6 to 9, 2026. Maximum temperatures are expected to reach 44-46 degrees Celsius. Heat Index may exceed 50 degrees due to combined heat and humidity effects. Health Advisory: Avoid all outdoor activity between 11am and 5pm. Drink minimum 3 litres of water per day. Wear loose light cotton clothing. Never leave children, elderly, or pets in parked vehicles — interior temperature reaches 70 degrees in 20 minutes. Construction sites must provide shade, water, and ORS to all workers. Night cooling centres are operational at 127 government schools across Delhi. ASHA workers are conducting daily doorstep wellness checks. Health helpline: 104.','all',1,1,'ORANGE ALERT: Severe heatwave 44-46 degrees across North India until April 9. Avoid outdoors 11am-5pm. Drink water every 30 mins. 127 cooling centres open in Delhi. Health helpline: 104.',NOW() - INTERVAL 1 DAY,NOW()),
('ADVISORY: M4.8 Earthquake Near Chamoli Uttarakhand','warning','The National Centre for Seismology has recorded a magnitude 4.8 earthquake at 02:34 IST today, with the epicentre located 42 km northeast of Chamoli, Uttarakhand at a shallow depth of 10 km. This falls in Zone V — India highest seismic risk category. No major damage or casualties have been reported so far. Aftershocks of magnitude 2.5 to 3.5 may occur in the coming 48 to 72 hours. Residents in Chamoli, Rudraprayag, Pithoragarh, and Bageshwar districts should inspect buildings for cracks especially at wall junctions, window corners, and where walls meet the ceiling or floor. Avoid entering cracked or damaged structures. Keep emergency kit accessible. DDMA helpline: 1800-180-4188.','all',1,1,'M4.8 earthquake near Chamoli Uttarakhand Zone V. Aftershocks possible 48-72 hrs. Inspect buildings for cracks. Avoid damaged structures. DDMA helpline: 1800-180-4188.',NOW() - INTERVAL 6 HOUR,NOW()),
('LANDSLIDE WARNING: NH-44 Blocked — Himachal Pradesh','warning','Extremely heavy rainfall of 210mm in 24 hours in Lahaul-Spiti and Kinnaur districts of Himachal Pradesh has triggered multiple landslides on NH-44 (Manali-Leh Highway) and NH-5 (Shimla-Kalka route). The Border Roads Organisation and HRTC have suspended all traffic between Rohtang Pass and Keylong until further notice. Approximately 800 tourists are currently stranded at Keylong and Sarchu rest houses. Helicopter rescue operations have commenced from Kullu Bhuntar airfield. Residents of Spiti Valley, Sangla Valley, and villages near the Satluj River basin must move to safer locations on higher ground immediately. Do not attempt to cross any flooded nullahs or streams on foot or by vehicle. District helpline Kullu: 01902-222340. HP Tourist helpline: 1100.','all',1,1,'WARNING: Multiple landslides on NH-44 Manali-Leh Highway. 800 tourists stranded. Helicopter rescue underway from Kullu. Avoid Rohtang Pass area entirely. HP Tourist helpline: 1100.',NOW() - INTERVAL 3 HOUR,NOW()),
('TSUNAMI WATCH: Andaman and Nicobar Islands','info','INCOIS has issued a Tsunami Watch for the Andaman and Nicobar Islands following a M7.1 undersea earthquake in the Sunda Trench at 15:22 UTC today. This is currently a WATCH status — not yet a full Warning. All coastal residents and tourists across the Andaman and Nicobar Islands should move away from beaches and low-lying coastal areas to higher ground immediately as a precaution. INCOIS is closely monitoring sea level gauges at Campbell Bay, Car Nicobar, and Port Blair. Estimated wave height if tsunami reaches the islands: 0.3 to 1.0 metres (moderate risk). All fishermen must return to port immediately. All scuba diving and snorkelling operations are suspended. Updates issued every 30 minutes on All India Radio Port Blair 684 kHz.','all',1,1,'TSUNAMI WATCH: Andaman and Nicobar Islands. M7.1 quake Sunda Trench. Move away from beaches to higher ground. Fishermen return to port now. AIR Port Blair 684 kHz for updates.',NOW() - INTERVAL 30 MINUTE,NOW()),
('HAZARDOUS AQI 418: Delhi-NCR Air Quality Emergency','info','Delhi and NCR districts including Gurgaon, Noida, Faridabad, and Ghaziabad have recorded an AQI of 418, classified as HAZARDOUS, due to a combination of stubble burning smoke from Punjab and Haryana and calm wind conditions trapping pollutants. PM2.5 concentration is currently 285 micrograms per cubic metre against the safe 24-hour limit of 25. GRAP Stage IV emergency restrictions are in force: all construction activity banned, schools and colleges operating in online mode, truck entry into Delhi restricted to essential goods, private vehicle odd-even scheme operational from 8am to 8pm. Health Advisory: Wear N95 or N99 masks outdoors — standard surgical masks do not filter PM2.5. Persons with asthma, heart disease, or diabetes and all children and elderly must stay strictly indoors. DPCC helpline: 1800-11-0093.','all',1,1,'HAZARDOUS AQI 418 Delhi-NCR. PM2.5 at 285 vs safe limit of 25. GRAP Stage IV active. Schools online. Wear N95 mask outdoors. Vulnerable groups stay indoors. DPCC: 1800-11-0093.',NOW() - INTERVAL 12 HOUR,NOW());

-- SHELTER LOCATIONS
INSERT INTO shelter_locations (name, address, latitude, longitude, capacity, type, contact, is_active, created_at, updated_at) VALUES
('Jagannathapur Multipurpose Cyclone Shelter','Jagannathapur Village, Puri District, Odisha 752107',19.8135,85.8312,3000,'cyclone','06752-223456',1,NOW(),NOW()),
('Rajendra Nagar Flood Relief Centre','Rajendra Nagar High School Campus, Patna, Bihar 800016',25.6093,85.1376,1500,'flood','0612-2223344',1,NOW(),NOW()),
('Bhachau Earthquake Relief Camp','Near Bhachau Railway Station, Kutch District, Gujarat 370140',23.2975,70.3384,2000,'earthquake','02836-262200',1,NOW(),NOW()),
('Kozhikode Civil Station Flood Shelter','Civil Station Complex, Beach Road, Kozhikode, Kerala 673020',11.2588,75.7804,800,'flood','0495-2371100',1,NOW(),NOW()),
('Tiruvallur District Cyclone Shelter','Government Higher Secondary School, Tiruvallur, Tamil Nadu 602001',13.1437,79.9132,2500,'cyclone','044-27662200',1,NOW(),NOW()),
('Mumbai Disaster Response Centre Kurla','MCGM Ward Office, LBS Marg, Kurla West, Mumbai 400070',19.0722,72.8798,1200,'flood','022-24044090',1,NOW(),NOW()),
('Gangtok Emergency Earthquake Shelter','SDMA Complex, MG Marg, Gangtok, Sikkim 737101',27.3389,88.6065,600,'earthquake','03592-202345',1,NOW(),NOW()),
('Visakhapatnam Port Cyclone Shelter','Port Area, Beach Road, Visakhapatnam, Andhra Pradesh 530001',17.6868,83.2185,4000,'cyclone','0891-2563000',1,NOW(),NOW()),
('Assam State Emergency Operations Centre','Dispur, Guwahati, Assam 781006',26.1433,91.7898,2000,'flood','0361-2237219',1,NOW(),NOW()),
('Chamoli District Earthquake Relief Camp','Near Gopeshwar Bus Stand, Chamoli, Uttarakhand 246401',30.4191,79.3124,500,'earthquake','01372-252007',1,NOW(),NOW()),
('Delhi Civil Defence Heatwave Cooling Centre Rohini','Government School Sector 16, Rohini, Delhi 110089',28.7353,77.1188,1000,'general','011-23490112',1,NOW(),NOW()),
('Chennai Corporation Flood Shelter Adyar','Corporation Office, Lattice Bridge Road, Adyar, Chennai 600020',13.0067,80.2563,1800,'flood','044-25383400',1,NOW(),NOW()),
('Imphal Landslide Relief Centre','SDRF Campus, Lamphel, Imphal West, Manipur 795004',24.7990,93.9368,400,'general','0385-2451525',1,NOW(),NOW()),
('Porbandar Coastal Cyclone Bunker','Fishermen Colony, Chowpatty, Porbandar, Gujarat 360575',21.6422,69.6019,1500,'cyclone','0286-2241234',1,NOW(),NOW()),
('Wayanad Landslide Emergency Camp Meppadi','Government Higher Secondary School, Meppadi, Wayanad, Kerala 673121',11.4534,76.1328,700,'general','04936-262200',1,NOW(),NOW());

-- DRILLS
INSERT INTO drills (type, date, building, participants, status, notes, created_by, created_at, updated_at) VALUES
('Earthquake Evacuation Drill','2026-04-08','IIIT Hyderabad Academic Block A, Gachibowli, Hyderabad',450,'scheduled','Annual mandatory earthquake drill for all students and faculty. Drop-Cover-Hold and staircase evacuation to assembly point at sports ground. NDRF trainer Mr. Suresh Kumar conducting briefing at 9:00 AM. Duration: 90 minutes including post-drill debriefing and written performance report.',1,NOW(),NOW()),
('Cyclone Preparedness Simulation','2026-04-10','Collectorate Building, Visakhapatnam, Andhra Pradesh',230,'scheduled','District-level cyclone response simulation with SDRF, Coast Guard Station Vizag, and Visakha Dairy. Scenario: Category 3 cyclone landfall in 36 hours. Mass evacuation coordination, shelter activation, supply pre-positioning at 15 shelters, and media briefing simulation. All 5 revenue divisional officers participating.',1,NOW(),NOW()),
('Hospital Mass Casualty Drill','2026-04-12','AIIMS Bhopal Trauma and Emergency Department',180,'scheduled','Disaster Medical Response drill simulating 50-casualty mass incident from railway accident. Triage using START protocol, hospital Emergency Operations Centre activation, coordination with 108 ambulance service, and family notification procedures. All ER and ICU staff mandatory. NDMA observer attending.',1,NOW(),NOW()),
('Fire Evacuation and Suppression Drill','2026-03-28','Infosys Campus Building 17 Electronic City Phase 2 Bengaluru',820,'completed','Quarterly fire drill per KSFE regulations. Scenario: electrical fire in server room. All 820 employees evacuated via 8 emergency staircases in 4 minutes 22 seconds against 5-minute target. Issue found: Emergency exit on 3rd floor east wing partially blocked. Corrective action issued to facilities team. All 12 fire wardens performed excellently.',1,NOW() - INTERVAL 9 DAY,NOW()),
('Flood Rescue Boat Operation Drill','2026-03-20','Bramhapuri Tehsil Headquarters, Chandrapur, Maharashtra',65,'completed','SDRF flood rescue team certification drill on Wardha River. Practiced: rapid boat deployment from trailer, casualty extraction from submerged vehicle, rooftop rescue using rope system, first aid in boat, and helicopter coordination by radio. All 65 SDRF personnel successfully recertified. 8 boats and 4 life-ring launchers deployed.',1,NOW() - INTERVAL 17 DAY,NOW()),
('School Earthquake Safety Programme','2026-03-15','Delhi Government School No 158, Mayur Vihar Phase 3',1200,'completed','NDMA School Safety Programme drill under National School Safety Programme. All 1200 students from Classes 1 to 12 participated. Drop-Cover-Hold drilled class-wise. 40 teachers trained as School Safety Marshals. Mock injury scenario with mannequins. District Magistrate East Delhi attended. School received NDMA School Safety Certificate.',1,NOW() - INTERVAL 22 DAY,NOW()),
('Industrial Chemical Spill Response Drill','2026-04-18','HPCL Refinery Mahul Mumbai Unit 4',120,'planned','Tier 2 mutual aid exercise simulating chlorine gas leak. Mumbai Fire Brigade HazMat team, MAHAD Industrial Cluster, and ONGC safety teams participating. PPE Level A suits deployed. Decontamination corridor at refinery gate. Evacuation of 800 metre radius simulated. MIDC Environment Officer observing.',1,NOW(),NOW()),
('Tsunami Coastal Evacuation Mock Drill','2026-04-20','Marina Beach Promenade, Chennai, Tamil Nadu',3500,'planned','INCOIS and Tamil Nadu State DDMA coordinating large coastal evacuation drill. 3500 fishermen and coastal residents evacuating to 8 designated tsunami vertical evacuation structures. Sirens tested at 10:00 AM. Coordination with Chennai Police, Revenue Department, and Fishing Harbour Authority.',1,NOW(),NOW()),
('Heatwave Response Protocol Training','2026-04-05','Rajkot Municipal Corporation Training Hall, Gujarat',95,'completed','Heat action plan training for 95 ASHA workers and health supervisors. Topics: recognizing heat exhaustion vs heatstroke, emergency cooling, ORS preparation, door-to-door wellness checks, data reporting. Conducted by Dr. Meena Joshi, District Medical Officer. Each participant received field kit with ORS sachets and thermometer.',1,NOW() - INTERVAL 1 DAY,NOW()),
('Night-time Earthquake Evacuation Drill','2026-05-02','Residential Township Sector 57, Gurugram, Haryana',2800,'planned','First-ever night-time earthquake drill in Gurugram at 2:00 AM. 2800 residents of 6 residential societies participating. Torch distribution to households on April 30. GMDA officials and Haryana SDMA coordinating. Objective: full building evacuation in under 8 minutes from any unit.',1,NOW(),NOW());

-- EMERGENCY KITS
INSERT INTO emergency_kits (user_id, item_name, category, quantity, is_checked, is_default, created_at, updated_at) VALUES
(1,'Drinking Water 4 litres per person per day for 3 days','Water and Food',12,1,1,NOW(),NOW()),
(1,'ORS Sachets Oral Rehydration Solution','Water and Food',20,1,1,NOW(),NOW()),
(1,'Water Purification Tablets halogen-based 50 tablets','Water and Food',50,1,1,NOW(),NOW()),
(1,'Ready-to-Eat Food Khakhra Energy Bars Rusk for 3 days','Water and Food',9,1,1,NOW(),NOW()),
(1,'Canned Food with Manual Can Opener','Water and Food',6,0,1,NOW(),NOW()),
(1,'Collapsible Water Container 10 litre BPA-free','Water and Food',2,1,1,NOW(),NOW()),
(1,'First Aid Kit NDMA Standard 50 items','Medical',1,1,1,NOW(),NOW()),
(1,'Prescription Medications personal 7-day supply','Medical',1,0,1,NOW(),NOW()),
(1,'Bandages Crepe 5cm and 10cm 3 rolls each','Medical',6,1,1,NOW(),NOW()),
(1,'N95 Masks for dust smoke and air pollution protection','Medical',10,1,1,NOW(),NOW()),
(1,'Antiseptic Solution Betadine 100ml and Dettol','Medical',2,1,1,NOW(),NOW()),
(1,'Essential Medicines Paracetamol ORS Antacid Antihistamine','Medical',1,1,1,NOW(),NOW()),
(1,'Sterile Examination Gloves 5 pairs','Medical',5,1,1,NOW(),NOW()),
(1,'CPR Face Shield and Pocket Mask','Medical',1,0,1,NOW(),NOW()),
(1,'Aadhaar Card Original and Photocopy in waterproof bag','Documents',1,1,1,NOW(),NOW()),
(1,'Passport Voter ID PAN Card copies laminated','Documents',1,0,1,NOW(),NOW()),
(1,'Property Documents and Insurance Papers copies','Documents',1,0,1,NOW(),NOW()),
(1,'Bank Account Details and Emergency Contacts laminated','Documents',1,1,1,NOW(),NOW()),
(1,'LED Torch Flashlight with Extra Batteries','Tools',2,1,1,NOW(),NOW()),
(1,'Battery-powered AM FM Radio for AIR emergency broadcasts','Tools',1,1,1,NOW(),NOW()),
(1,'Emergency Whistle Pealess 120dB one per family member','Tools',3,1,1,NOW(),NOW()),
(1,'Multi-tool Swiss Army Knife','Tools',1,1,1,NOW(),NOW()),
(1,'Adjustable Wrench to shut off gas and water mains','Tools',1,0,1,NOW(),NOW()),
(1,'Heavy-duty Nylon Rope 15 metres','Tools',1,0,1,NOW(),NOW()),
(1,'Work Gloves Heavy Leather for debris protection','Tools',2,1,1,NOW(),NOW()),
(1,'Emergency Mylar Blanket retains 90 percent body heat','Shelter',4,1,1,NOW(),NOW()),
(1,'Waterproof Tarpaulin and Rain Poncho','Shelter',2,0,1,NOW(),NOW()),
(1,'Change of Clothes per person in waterproof bag','Shelter',3,0,1,NOW(),NOW()),
(1,'Sturdy Closed-toe Shoes extra pair','Shelter',1,1,1,NOW(),NOW()),
(1,'Power Bank 20000 mAh minimum fully charged','Communication',1,1,1,NOW(),NOW()),
(1,'Emergency Contact List printed and laminated','Communication',2,1,1,NOW(),NOW()),
(1,'City and District Paper Maps not only digital','Communication',1,0,1,NOW(),NOW()),
(1,'Prepaid SIM Card BSNL backup network','Communication',1,0,1,NOW(),NOW());

-- ENROLLMENTS (using real user IDs 1-15 and real course IDs)
INSERT INTO enrollments (user_id, course_id, enrolled_at) VALUES
(1,1,NOW() - INTERVAL 25 DAY),
(1,11,NOW() - INTERVAL 20 DAY),
(1,12,NOW() - INTERVAL 15 DAY),
(1,2,NOW() - INTERVAL 10 DAY),
(2,1,NOW() - INTERVAL 22 DAY),
(2,2,NOW() - INTERVAL 15 DAY),
(2,16,NOW() - INTERVAL 8 DAY),
(3,12,NOW() - INTERVAL 18 DAY),
(3,13,NOW() - INTERVAL 12 DAY),
(4,11,NOW() - INTERVAL 10 DAY),
(4,17,NOW() - INTERVAL 6 DAY),
(5,2,NOW() - INTERVAL 8 DAY),
(5,16,NOW() - INTERVAL 5 DAY),
(6,12,NOW() - INTERVAL 7 DAY),
(7,13,NOW() - INTERVAL 5 DAY),
(8,1,NOW() - INTERVAL 4 DAY),
(9,2,NOW() - INTERVAL 3 DAY),
(10,16,NOW() - INTERVAL 2 DAY);

-- PROGRESS (module_id must match IDs auto-assigned above — using 1-based after truncate)
INSERT INTO progress (user_id, course_id, module_id, completed, completed_at) VALUES
(1,1,1,1,NOW() - INTERVAL 24 DAY),
(1,1,2,1,NOW() - INTERVAL 22 DAY),
(1,1,3,1,NOW() - INTERVAL 18 DAY),
(1,1,4,1,NOW() - INTERVAL 10 DAY),
(1,11,5,1,NOW() - INTERVAL 19 DAY),
(1,11,6,1,NOW() - INTERVAL 16 DAY),
(1,11,7,1,NOW() - INTERVAL 12 DAY),
(2,1,1,1,NOW() - INTERVAL 21 DAY),
(2,1,2,1,NOW() - INTERVAL 18 DAY),
(2,1,3,1,NOW() - INTERVAL 14 DAY),
(2,1,4,1,NOW() - INTERVAL 7 DAY),
(3,12,9,1,NOW() - INTERVAL 17 DAY),
(3,12,10,1,NOW() - INTERVAL 14 DAY),
(3,12,11,1,NOW() - INTERVAL 10 DAY),
(5,2,5,1,NOW() - INTERVAL 7 DAY),
(5,2,6,1,NOW() - INTERVAL 5 DAY),
(5,2,7,1,NOW() - INTERVAL 3 DAY),
(5,2,8,1,NOW() - INTERVAL 1 DAY);

-- CERTIFICATES
INSERT INTO certificates (user_id, course_id, score, cert_code, issued_at) VALUES
(1,1,91,'PREP-GEN-2026-HR001',NOW() - INTERVAL 10 DAY),
(1,11,89,'PREP-FLOOD-2026-HR002',NOW() - INTERVAL 8 DAY),
(2,1,80,'PREP-GEN-2026-PS001',NOW() - INTERVAL 7 DAY),
(2,2,88,'PREP-FA-2026-PS002',NOW() - INTERVAL 2 DAY),
(3,12,93,'PREP-EQ-2026-AN001',NOW() - INTERVAL 5 DAY),
(3,13,87,'PREP-CYC-2026-AN002',NOW() - INTERVAL 1 DAY),
(5,2,90,'PREP-FA-2026-RG001',NOW() - INTERVAL 1 DAY);

-- DISASTER REPORTS
INSERT INTO disaster_reports (user_id, disaster_type, location, description, severity, status, latitude, longitude, created_at, updated_at) VALUES
(1,'Landslide','Mundakkai and Chooralmala, Wayanad District, Kerala','On July 30 2024 two catastrophic landslides struck Mundakkai and Chooralmala villages at 2 AM while residents slept. Triggered by 572mm of rainfall in 48 hours — 400 percent above normal — saturating slopes largely deforested for tea and coffee plantations. 231 people were killed and 10,000 displaced. Approximately 280 houses and four bridges were destroyed. Indian Army, NDRF, Kerala Fire Force, and volunteers conducted rescue operations for 10 days. Primary causes: extreme rainfall, degraded forest cover on steep slopes, and complete absence of early warning systems. GSI now recommends mandatory slope stability assessments for all plantation areas in seismic Zone V.','critical','resolved',11.4534,76.1328,NOW() - INTERVAL 250 DAY,NOW()),
(1,'Cyclone','Nellore and Bapatla Districts AP and Chennai Tamil Nadu','Cyclone Michaung made landfall near Bapatla AP on December 5 2023 with sustained winds of 90-100 km/h causing unprecedented flooding in Chennai — worst in 8 years. Adyar and Cooum rivers overflowed, flooding Velachery, Mudichur, and Anna Nagar East. Two million people affected across AP and Tamil Nadu. 17 deaths reported — far fewer than the 500 deaths in 2015 Chennai floods due to improved early warning and NDRF pre-positioning. Key lesson: storm drain capacity and Pallikaranai wetlands conservation are critical for Chennai flood resilience.','high','resolved',13.9299,79.9800,NOW() - INTERVAL 120 DAY,NOW()),
(1,'Heatwave','Delhi NCR, Rajasthan, Haryana, Punjab and Western UP','Prolonged heatwave April 1-9 2026 brought temperatures of 44-46 degrees Celsius across North India. Eight heat-related deaths reported. An estimated 45 million people affected across five states. Hospitals reported 340 percent increase in heat exhaustion cases. IMD issued advance Orange and Red alerts with 72-hour notice. Response: 127 cooling centres in Delhi, ORS at 450 community centres, 89000 doorstep wellness checks by ASHA workers, and 2.3 lakh water bottles distributed daily to construction labourers. Earliest severe April heatwave on record in Delhi since 1901.','high','reviewing',28.6139,77.2090,NOW() - INTERVAL 5 DAY,NOW()),
(7,'Flood','Chamoli District Uttarakhand — Rishi Ganga and Dhauliganga Valleys','February 7 2021: Glacier Lake Outburst Flood devastated Rishi Ganga and Dhauliganga valleys. Ice and rock mass detached from Nanda Devi glacier, triggering a flood surge at over 100 km/h through narrow Himalayan gorges. Tapovan-Vishnugad hydropower project (NTPC) and Rishi Ganga power project were completely destroyed. 204 persons killed or missing including 136 labourers at power projects. NDRF rescued 12 persons trapped in powerhouse tunnel over 72 hours. This disaster highlights extreme risks of large infrastructure in ecologically sensitive glacier zones and urgent need for GLOF early warning network.','critical','resolved',30.4191,79.3124,NOW() - INTERVAL 1800 DAY,NOW()),
(7,'Earthquake','Bhuj Anjar Bhachau Rapar in Kutch District Gujarat','The M7.7 Bhuj earthquake struck January 26 2001 at 08:46 AM IST on Republic Day killing 20,085 people and injuring 166,000. India most deadly earthquake since 1950. Entire towns of Bhuj, Anjar, and Bhachau were devastated. Over 600,000 homes destroyed and 1 million damaged. The disaster directly led to creation of Gujarat State Disaster Management Authority as the first state DMA in India, which became the model for the National Disaster Management Act 2005 and NDMA. BIS updated IS 1893 seismic building codes and comprehensively revised India earthquake zone map as a direct result.','critical','resolved',23.2420,69.6669,NOW() - INTERVAL 9200 DAY,NOW()),
(1,'Flood','Mumbai Maharashtra — Entire Metropolitan Area','July 26 2005 Mumbai deluge: 944mm of rainfall in 24 hours at Santacruz — highest single-day rainfall ever recorded in India. City paralysed: trains stranded, roads submerged, airport closed, power cut across most areas. 1094 people killed from drowning, building collapse, and electrocution. Twenty million residents affected. Economic loss estimated at Rs 15000 crore. Led directly to Brihanmumbai Storm Water Drainage project, construction of retention lakes, and establishment of Mumbai Disaster Management Plan. Annual storm drain vulnerability audits are now mandatory for all BMC wards.','critical','resolved',19.0760,72.8777,NOW() - INTERVAL 7500 DAY,NOW());

-- RESOURCES
INSERT INTO resources (title, type, url, description, category, created_by, created_at, updated_at) VALUES
('NDMA India — National Disaster Management Guidelines','link','https://ndma.gov.in/Natural-Hazards','Official NDMA guidelines for all major disaster types. Includes district-level disaster management plans and training materials for all Indian states and union territories.','General',1,NOW(),NOW()),
('IMD Cyclone Tracker — Live Monitoring','link','https://mausam.imd.gov.in/imd_latest/contents/cyclone.php','India Meteorological Department real-time cyclone monitoring portal. Track active cyclones, view 5-day track forecasts, and download official IMD bulletins with wind speed and storm surge predictions.','Cyclone',1,NOW(),NOW()),
('INCOIS Tsunami Warning Portal','link','https://tsunami.incois.gov.in','Indian National Centre for Ocean Information Services. Real-time tsunami warnings, sea level gauge data, and coastal inundation maps for the Indian Ocean region.','Tsunami',1,NOW(),NOW()),
('CWC Flood Monitoring — India WRIS','link','https://indiawris.gov.in','Central Water Commission real-time data from over 5000 river gauging stations. Check flood warning status, current water levels versus danger levels, and discharge data for rivers in your district.','Flood',1,NOW(),NOW()),
('GSI Landslide Atlas of India — Bhuvan Portal','link','https://bhukosh.gsi.gov.in','Geological Survey of India interactive hazard mapping portal. View landslide susceptibility zones, active landslide inventory, and geological hazard maps by district and state.','Landslide',1,NOW(),NOW()),
('Sachet — NDMA Multi-Hazard Early Warning App','link','https://sachet.ndma.gov.in','NDMA official multi-hazard early warning system. Register your location to receive alerts for cyclones, floods, earthquakes, heatwaves, and other hazards in 12 Indian languages.','General',1,NOW(),NOW()),
('WHO First Aid Guidelines 2023','document','https://www.who.int/publications/i/item/9789240081727','World Health Organization updated first aid guidelines covering CPR, wound care, fractures, burns, heatstroke, snakebite, and drowning. International evidence-based standards used by NDRF.','Medical',1,NOW(),NOW()),
('India AQI — CPCB Real-time Air Quality','link','https://app.cpcbccr.com/AQI_India/','Central Pollution Control Board live AQI monitoring for all Indian cities. Monitor PM2.5, PM10, NO2, and SO2 levels. Essential reference during heatwaves and industrial pollution emergencies.','Heatwave',1,NOW(),NOW()),
('NDMA Earthquake Safety Videos Hindi and English','video','https://ndma.gov.in/Awareness/Videos','Official NDMA earthquake preparedness videos demonstrating Drop-Cover-Hold technique, building evacuation, search and rescue basics, and post-earthquake safety checks in 8 Indian languages.','Earthquake',1,NOW(),NOW()),
('ISRO Bhuvan Disaster Services — Satellite Imagery','link','https://bhuvan.nrsc.gov.in/disaster/','ISRO satellite imagery for real-time disaster monitoring. View flood inundation maps, cyclone damage assessment, and landslide mapping using Cartosat and Resourcesat-2 data.','General',1,NOW(),NOW()),
('NDRF Flood Rescue Operations Manual','document','https://ndrf.gov.in/sites/default/files/training_manual.pdf','Official NDRF training manual for flood rescue covering boat deployment, swift water rescue, rooftop casualty extraction, field first aid, and post-flood health protocols.','Flood',1,NOW(),NOW()),
('Kerala SDMA Flood Preparedness Guide','link','https://sdma.kerala.gov.in','State Disaster Management Authority Kerala comprehensive flood guide. Pre-monsoon household checklist, evacuation to safe zones, relief camp procedures, and post-flood recovery in Malayalam and English.','Flood',1,NOW(),NOW());

